#!/bin/bash
ch=$(ls -1 "/bedrock/strata/arch/opt/JetBrains/apps/CLion/" | sort -V | tail -1)
dir=$(ls -1 "/bedrock/strata/arch/opt/JetBrains/apps/CLion/$ch/" | sort -V | tail -1)
/bedrock/strata/arch/opt/JetBrains/apps/CLion/$ch/$dir/bin/clion.sh </dev/null &>/dev/null &
